global:
  scrape_interval: 15s

external_labels:
  hostname: "${HOSTNAME}"

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]

remote_write:
  - url: "${PROM_REMOTE}"
    tls_config:
      insecure_skip_verify: true