global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
#Bật remote_write 
remote_write:
    - url: http://192.168.88.124:9090/api/v1/write
    tls_config:
      insecure_skip_verify: true