global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
#Bật remote_write đẩy về server quản lý 
remote_write:
    - url: https://prometheus.yway.vn/api/v1/write
    tls_config:
      insecure_skip_verify: true