global:
  scrape_interval: 15s

  external_labels:
    hostname: "${SERVER_NAME}"

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]

remote_write:
  - url: "${SERVER_REMOTE}"